apiVersion: v1
kind: Service
metadata:
  name: drug-database-service
  namespace: drug-interaction-system
  labels:
    app: drug-database-service
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: http
  selector:
    app: drug-database-service






