apiVersion: v1
kind: Service
metadata:
  name: interaction-service
  namespace: drug-interaction-system
  labels:
    app: interaction-service
spec:
  type: ClusterIP
  ports:
  - port: 9002
    targetPort: 9002
    protocol: TCP
    name: http
  selector:
    app: interaction-service






